---
title: Spatio-temporal estimates of HIV risk group proportions for adolescent girls and young women across 13 priority countries in sub-Saharan Africa
author:
  - name: Adam Howes
    email: ath19@ic.ac.uk
    affiliation: [A, B]
    corresponding: ath19@ic.ac.uk
  - name: Kathryn A. Risher 
    affiliation: [C, B]
  - name: Van Kính Nguyen
    affiliation: B
  - name: Oliver Stevens
    affiliation: B
  - name: Katherine M. Jia
    affiliation: D
  - name: Timothy M. Wolock
    affiliation: [A, B]
  - name: Lycias Zembe
    affiliation: E
  - name: Ian Wanyeki
    affiliation: E
  - name:  Mary Mahy
    affiliation: E
  - name: Clemens Benedikt
    affiliation: E
  - name: Seth R. Flaxman
    affiliation: F
  - name: Jeff W. Eaton
    affiliation: B
address:
  - code: A
    address: Department of Mathematics, Imperial College London
  - code: B
    address: MRC Centre for Global Infectious Disease Analysis, School of Public Health, Imperial College London
  - code: C
    address: Department of Medical Social Sciences, Feinberg School of Medicine, Northwestern University
  - code: D
    address: Harvard T. H. Chan School of Public Health, Harvard University
  - code: E
    address: Joint United Nations Programme on HIV/AIDS, Geneva, Switzerland
  - code: F
    address: Department of Computer Science, University of Oxford
abstract: |
  **Background:**
  The Global AIDS Strategy 2021-2026 identifies adolescent girls and young women (AGYW) as a priority population for   HIV prevention and recommends differentiating intervention portfolios geographically based on local HIV incidence   and individual risk behaviours.

  **Methods:**
  We analysed 47 geospatially referenced national household surveys conducted between 1999-2018 across 13 Global   Fund priority countries in sub-Saharan Africa.
  Female survey respondents aged 15-29 years were classified into four risk groups (not sexually active, cohabiting, non-regular partner[s] and female sex workers) based on reported sexual partnerships.
  We used a Bayesian spatio-temporal multinomial regression model to estimate the proportion of AGYW in each risk group stratified by district, year and five-year age group.
  We then assessed the efficiency of prioritising interventions according to these risk groups.

  **Results:**
  Data consisted of $291,465$ female survey respondents aged 15-29.
  Risk group proportions varied substantially across age groups (44.6\% of variation), countries (28.7\%), and between districts within each country (20.6\%), but changed little over time (1.6\%).
  Among women aged 20-29, we found a geographic delineation, north of which in eastern Africa, cohabiting (69.5\%) is more common than non-regular partner(s) (13.3\%), and south of which, non-regular partner(s) (52.6\%) are more common than cohabiting (27.9\%).
  Prioritisation based on behavioural risk, on top of location and age based prioritisation, reduced the proportion of population that must be reached to find half of all new infections from 20.1\% to 10.4\%.
  Female sex workers were 2.4\% of the at risk population but 15.9\% of all new infections.

  **Conclusions:**
  Our risk group estimates provide data for HIV programmes to implement a differentiated prevention approach and set targets according to the Global AIDS Strategy.
  Successfully implementing this approach would result in finding substantially more infections, particularly among female sex workers.
author_summary: |
  Author summary

bibliography: citations.bib
output: rticles::plos_article
header-includes:
- \usepackage{tabularx}
# # plos.csl can be download and used locally
# csl: http://www.zotero.org/styles/plos
---

# Introduction

In sub-Saharan Africa, adolescent girls and young women (AGYW) aged 15-29 are `r "num"`\% of the population but `r "num"`\% of new HIV infections [@unaids2021update].
HIV incidence amongst AGYW is `r "num"` times higher than among similarly aged males due to younger age at first sex, age patterns of sexual mixing, structural vulnerability and power imbalances, and increased susceptibility to HIV infection [@joint2016hiv].
AGYW have therefore been identified as a priority population for HIV primary prevention, and significant investments have been made in prevention programming [@saul2018dreams; @global2018measurement].

HIV prevention for AGYW is typically comprised of basic programming which is made available to all, together with additional, more intensified, programming which is differentiated on the basis of risk [@joint2016hiv, birdthistle2018evaluating].
To maximize the impact of additional programming, often comprised of more costly interventions, delivery should be prioritised towards those at the highest risk level.
As both community-level epidemic indicators and individual-level behaviours determine risk of acquiring HIV, it is important to consider both of these factors in tandem to enable more efficient prioritisation of prevention services [@anderson2014maximising; @mcgillen2016optimum; @kelly2018global; @jia2022risk].

The Global AIDS Strategy 2021-2016 [@unaids2021global], adopted by the UN General Assembly in June 2021, proposed stratifying provision of HIV prevention to AGYW based on both population-level HIV incidence in the local population and individual-level sexual risk behaviour.
Four prioritisation strata (Table) are defined based on: (1) subnational annual incidence (<0.3\%, 0.3-1\% and >3\%), and (2) self-reported high-risk behaviour or recent STI infection.
The strategy encourages programmes to  define targets for the proportion of AGYW to be reached with a range of interventions (Table) based upon this prioritisation strata [@unaids2021global].
These interventions may include STI screening and treatment, access to pre-exposure prophylaxis (PrEP), access to post-exposure prophylaxis (PEP), comprehensive sexuality education, and economic empowerment.

Implementation of the strategy by national HIV programmes and stakeholders requires data on the population size and HIV incidence in each risk group, age group, and district to determine prioritisation for stratified HIV prevention.
We developed a multivariate Bayesian spatio-temporal model to estimate the proportion of AGYW aged 15-29 years in four behavioural risk groups, stratified by district, year, and five-year age group.
We focused on 13 countries in sub-Saharan Africa which have been identified by by the Global Fund to Fight AIDS, TB, and Malaria [@global2018measurement] as priority countries for implementation of AGYW HIV prevention.
Our methodology is standardised across countries, allowing prioritisation both within and between countries.
We analysed the extent to which the risk group proportions varied across districts, age groups, between countries, and over time.
Using our estimates, we calculated the number of new infections in each risk, age, and district strata using population size data, incidence rate ratios, and expected incidence projections.
Finally, we quantified the increased efficiency in terms of the expected number of new infections that could be preemptively reached by stratified prioritisation of interventions.

# Methodology

## Data

We analysed nationally-representative household survey data from 13 countries: Botswana, Cameroon, Kenya, Lesotho, Malawi, Mozambique, Namibia, South Africa, Eswatini, Tanzania, Uganda, Zambia and Zimbabwe.
We included surveys conducted in these countries in the years 1999-2018 in which women were interviewed about their sexual behaviour and sufficient geographic information was available to locate survey clusters to districts.
Demographic and Health Surveys (DHS), AIDS Indicator Surveys (AIS), Population-based HIV Impact Assessment (PHIA) surveys, and the Botswana HIV/AIDS Impact Survey 2013 (BAIS) were included.

For each survey, we classified respondents into one of four behavioural risk groups according to reported sexual risk behaviour in the past 12 months.
These risk groups were: not sexually active, one cohabiting sexual partner, at least one non-regular sexual partner, and AGYW who are female sex workers (FSW) (Table, Figure).
In the case of inconsistent responses, women were categorised according to the highest risk group they fell into, ensuring that the categories were mutually exclusive.
Exact survey questions varied to a limited extent between surveys, as described in Appendix.
Questions captured information about if the respondent had been sexually active in the past twelve months, and if so how with many partners.
For their three most recent partners, respondents were also asked about the type of partnership (spouse, cohabiting partner, partner not cohabiting with respondent, friend, sex worker, sex work client, and other).

Some surveys included a specific question asking if the respondent had received or given payment for sex in the past twelve months; in these surveys, 2.64\% of women reported transactional sex.
In surveys without that question, women almost never (0.01\%) answered that one of their three most recent partners was a sex work client.
For this reason, we did not include surveys without a specific transactional sex question when estimating the proportion of the population who were FSW or engaged in transactional sex.

We used estimates of population, people living with HIV (PLHIV) and new HIV infections stratified by district and age group from outputs of the Naomi model [@eaton2021naomi].
The model synthesises data from multiple sources to produce consistent subnational estimates of indicators of interest, and has been used by countries as a part of the HIV estimates process supported by UNAIDS.
The administrative area hierarchy and geographic boundaries we used correspond to those used in Naomi.
In Cameroon and Kenya we used an analysis level one higher than used in Naomi.

## Two-stage risk group proportion model

To estimate the proportion of AGYW in each risk group we took a two-stage modelling approach, further details of which are provided in Appendix.
First, we fit a spatio-temporal multinomial model stratified by district, year (1999-2018) and five-year age group (15-19, 20-24 and 25-29) for the proportion of AGYW in three categories: (1) not sexually active, (2) cohabiting, and (3) either non-regular partner(s) or transactional sex.
Combining the two highest risk groups in this way allowed data from all 47 surveys to be included in this first stage model.
Second, we fit a spatial logistic regression model separating those who have non-regular parnter(s) from those who have had transactional sex, stratified by district, and five-year age group, and using only data from the 13 surveys with a specific transaction sex question.
As these surveys were only available in the years 2013-2018, we assumed the proportion in the very high risk group among those in at least the high risk group was constant over time.
We combined the two models using 1000 samples from each posterior distribution to produce samples from all four risk groups.
Finally, we adjusted the samples from the transactional sex category to match age-country specific FSW population size estimates, modifying the samples from the non-regular partner(s) category such that the proportions sum to one.
To do so, we disaggregated national 15-49 FSW population size estimates from @stevens2022estimating using the FSW age distribution in South Africa from the Thembisa model [@johnson2020thembisa] in combination with country-specific age at first sex distributions from @kinh2021trends.

<!-- \text{Gamma}(\alpha = 10.4, \beta = 0.36)$ FSW age distribution -->

We considered eight model specifications for the space-age-time multinomial model for the three risk groups (Table).
All models included intercepts for each risk group, age, country, and age-country effects, a spatial effect allowing variation by district, and a temporal effect allowing variation over time.
Alternative models varied the specification for the spatial effect between independent spatial effects versus spatially correlated effects and independent temporal effects versus first-order auto-regressive temporal effects.
Each alternative was considered with an additional spatio-temporal interaction term allowing the temporal trend to vary across districts.
To understand the importance of each part of the model we undertook a variance-based sensitivity analysis using the random effect variance parameters.

For the logistic regression model for the proportion engaging in transactional sex among those with non-regular partner(s), we considered six specifications (Table).
Each included an intercept, age and country effects, and a spatial effect allowing district level variation.
Both independent and spatially correlated spatial effects were considered.
To improve estimation with sparse data, we considered model alternatives with national-level covariates for either the proportion of men who reported ever having paid for sex or having paid for sex in the last twelve months, available from @hodgins2022population.

We performed inference using integrated nested Laplace approximation [@rue2009approximate] via the `R-INLA` package [@martins2013bayesian].
The best performing model was selected according to the conditional predictive ordinate (CPO) criteria, a measure of leave-one-out model performance that can be calculated directly in `R-INLA` without explicit model refitting [@held2010posterior].
The \textsc{R} [@r] code used to implement the models and produce  results is available from `github.com/athowes/multi-agyw`.
We used the `orderly` package [@orderly] for reproducible research.

## Prevalence, incidence and new infections

We used the risk group proportion estimates to calculate HIV prevalence, PLHIV, HIV incidence and number of new HIV infections stratified according to district, age group and risk group by disaggregating estimates from the Naomi model (further details are provided in Appendix).

We disaggregated HIV prevalence estimates by risk group on the logit scale using age-country prevalence log-odds ratios calculated from survey bio-marker data. 
Logit scaling was preferred to linear scaling, as linear scaling resulted in some strata having prevalence above 100\%.
PLHIV were calculated by multiplying HIV prevalence by risk group population size.

HIV incidence estimates were disaggregated by risk group on the linear scale using the HIV infection risk ratios given in Table.
Number of new HIV infections were calculated by multiplying HIV incidence by susceptible risk group population size. 
We then calculated the number of new infections that would be found per person reached when prioritising according to incidence under each possible risk stratification.
In doing so, we implicitly assumed it is possible to reach all members of a strata.

# Results

## Data

We included 47 surveys in our analysis (Figure, Table), with a total sample size of `r "num"` women aged 15-29 years (`r "num"` aged 15-19 years, `r "num"` aged 20-24 years, and `r "num"` aged 25-29 years).
Of these, 13 surveys included a specific transactional sex question, with corresponding sample size `r "num"` (`r "num"` aged 15-19 years, `r "num"` aged 20-24 years, and `r "num"` aged 25-29 years).
The median number of surveys per country was four, ranging from one in Botswana and South Africa to six in Uganda.
Direct estimates of the four risk group proportions from these surveys were highly correlated with our modelled estimates at a national-level (Figures).

## Model selection

The best fitting multinomial regression model included correlated spatial effects and first-order autoregressive temporal effects, but not spatio-temporal interactions.
The best logistic regression model for transactional sex included correlated spatial effects and the proportion of men who reported ever paying for sex covariate.
Model performance according to the CPO criteria for each of the considered models is provided in the appendix (Figures, Tables).

Posterior mean estimates for our final model in the most recent year, 2018, are shown as choropleths (Figure) and dotplots (Figure).
In the following results, all estimates refer to 2018, the most recent year included in our analysis, unless otherwise indicated.
Posterior mean, median, upper (97.5\%) and lower (2.5\%) credible estimates for each district, age group and year from our final model are provided in the supplementary material.

## Spatial, temporal and age trends

In most districts (`r "num"`\%; 95\% credible interval [CI] `r "num"`--`r "num"`\%) adolescent girls aged 15-19 were not sexually active.
The exception was Mozambique, where the majority (`r "num"`\%; 95\% CI `r "num"`--`r "num"`\%) were sexually active in the past year and close to a third (`r "num"`\%; 95\% CI `r "num"`--`r "num"`\%) were cohabiting with a partner.

In the 20-24 and 25-29 year age groups, the majority (`r "num"`\%; 95\% CI `r "num"`--`r "num"`\%) of women were either cohabiting or had non-regular partner(s).
Countries in east and central Africa (Cameroon, Kenya, Malawi, Mozambique, Tanzania, Uganda, Zambia and Zimbabwe) had a higher proportion of women in these age groups cohabiting (`r "num"`\%, as compared with `r "num"`\% with non-regular partner[s]) and countries in southern Africa (Botswana, Eswatini, Lesotho, Namibia and South Africa) had a higher proportion with non-regular partner(s) (`r "num"`\%, as compared with `r "num"`\% cohabiting).
There was a clear geographic delineation along the border of Mozambique, through the interior of Zimbabwe and along the border of Zambia.

The median proportion of FSW nationally was `r "num"`\% (95\% CI `r "num"`--`r "num"`\%) for the 15-19 age group, compared with $2.4\%$ (95\% CI `r "num"`--`r "num"`\%) and `r "num"`\% (95\% CI `r "num"`--`r "num"`\%) for the 20-24 and 25-29 age groups respectively.
This age pattern, reflecting the lower proportion sexually active among those aged 15-19 years, was the foremost effect of adjusting our estimates to match [@johnston2022deriving]; in contrast, our initial estimates of transactional sex were close to constant by age (Figure~\ref{fig:fsw-within-between-country-variation}).

##

Age explained `r "num"`\% (95\% CI `r "num"`--`r "num"`\%) of the variation in risk group proportions, country explained `r "num"`\% (95\% CI `r "num"`--`r "num"`\%), and district explained `r "num"`\% (95\% CI `r "num"`--`r "num"`\%).
The temporal effects only explained `r "num"`\% (95\% CI `r "num"`--`r "num"`\%) of variation, indicating very little change in risk group proportions over time, with the remaining `r "num"`\% (95\% CI `r "num"`--`r "num"`\%) attributable to the category random effects.
We observed similar variance decomposition results fitting each country individually (Figure~\ref{fig:aaa-variance-proportions}) or using other model specifications.

<!-- Can you please write another paragraph here calling out some examples of the amount of variation? -->
<!-- Awaiting additional results: https://github.com/athowes/multi-agyw/issues/95 -->

## Infections reached

For any given fraction of AGYW prioritised, substantially more new infections were reached by strategies that included behavioural risk stratification.
Reaching half of all new infections required reaching 20.1\% of the population when stratifying by area and age, but only 10.4\% when behavioural stratification was included (Figure~\ref{fig:infections-reached}).
The majority of this benefit came from reaching FSW, who were 2.4\% of the population but 15.9\% of all new infections.

Efficiency was reduced if prioritisation was done separately by country.
On average, reaching half of new infections in a country required reaching 15.7\% (range 7.8-23.4\%) of the population when stratifying by area and age, reducing to 5.1\% (range 1.3-9.2\%) when behaviour was included.
The importance of stratifying risk upon age, location and behaviour within a country varied (Figure~\ref{fig:infections-reached-country-1}--Figure~\ref{fig:infections-reached-country-13}), analogous to the varying contribution of each to the total variance (Section~\ref{sec:variance-decomp}).
For example, FSW in Tanzania were estimated to be 5.3\% of the population and close to half (41.4\%) of all new infections, whereas FSW in Namibia were just 0.3\% of the population and 2.7\% of all new infections.

# Discussion

We estimated sexual risk group proportions for AGYW at a district-level in 13 sub-Saharan African countries with pressing HIV prevention requirements.
Our estimates will enable country and district-level planners to differentiate prevention programming according to risk behaviour, as outlined in the Global AIDS Strategy.

<!-- Comment about how novel this would be if implemented -->

By considering all possible risk stratification strategies, we showed that successful implementation of a risk-stratified approach would allow substantially more new infections to be found before they occur.
A considerable proportion of these new infections are among FSW, supporting the case for HIV programming efforts focused on key population groups [@baral2012burden].
We showed that there is substantial variation in the importance of prioritisation by age, location and behaviour within each country.
This highlights the importance of understanding and tailoring HIV prevention efforts to country-specific contexts.
By standardising our analysis across all 13 countries, we showed the additional efficiency benefits of resource allocation between countries.

We found a geographic delineation in the proportion of women cohabiting between southern and eastern Africa, calling attention to a divide attributable to many cultural, social and economic factors.
The delineation does not represent a boundary between predominately Christian and Muslim populations, which is further north.
We also note that the high numbers of adolescent girls aged 15-19 cohabiting in Mozambique, reflecting existing concerns [@unicef].

Our modelled estimates improve upon direct survey results for three reasons.
First, by taking a modular modelling approach, we integrated all relevant survey information from multiple years, allowing estimation of the FSW proportion for surveys without a specific transactional sex question.
Second, whereas direct estimates exhibit large sampling variability at a district level, we alleviated this issue using spatio-temporal smoothing (Figure).
Third, we provide estimates in all settings, including districts without any survey clusters as well as years without surveys, allowing estimates to be consistently fed into further analysis and planning pipelines.

To the best of our knowledge, the only previous research to geographically map AGYW HIV risk groups is @brugh2021characterizing, who use biomaker and behavioural data from the most recent surveys in Eswatini, Haiti and Mozambique to define and subsequently map risk groups.

This work serves as a case-study in how to use the multinomial-Poisson transformation to efficiently specify and fit multinomial spatio-temporal models in `R-INLA`.
We used Kronecker products over Gaussian Markov random fields to define appropriate category-specific spatio-temporal random effects.

<!-- Paragraph about AGFS e.g. our results are consistent with age at first sex findings [@kinh2021trends]. -->

## Limitations

Our analysis of the number of infections that could be reached by each risk stratification strategy was based on simplifying assumptions and should be interpreted as illustrating the potentially obtainable benefits, rather than benefits that would be accrued from any specific intervention strategy.
Factors we did not consider include the greater administrative burden of more complex strategies, variation in difficulty or feasibility of reaching individuals in each strata, variation in the range or effectiveness of interventions by strata, and changes in strata membership that may occur during the course of a year.

<!-- Dependence of FSW on clustering and migration. -->

Under-reporting of higher risk sexual behaviours amongst AGYW could affect the validity of our estimates.
Due to social stigma or disapproval, respondents may be reluctant to report non-marital partners [@nnko2004secretive} or may bias their reporting of sexual debut [@zaba2004age; @wringe2009comparative; @kinh2021trends].
For guidance of resource allocation, differing rates of under-reporting by country, district, year or age group are particularly concerning to the applicability of our results; and, while it may be reasonable to assume a constant rate over space-time, the same cannot be said for age, where aspects of under-reporting have been shown to decline as respondents age [@glynn2011assessing], suggesting that the elevated risks we found faced by younger women are likely a conservative estimate.
Furthermore, our FSW estimates do not overcome the difficulties of sampling hard to reach groups; in particular, the possibility of being excluded from household sampling frames.

<!-- I think the Nnko 2004 is a good cite. For biases in age at first sex as folks age: -->
<!-- https://pubmed.ncbi.nlm.nih.gov/15572637/ -->
<!-- https://pubmed.ncbi.nlm.nih.gov/19307342/ -->
<!-- Then these are all about how methodological approaches can result in different estimates (I think): -->
<!-- Hewett PC, Mensch BS, Erulkar AS. Consistency in the reporting of sexual behaviour by adolescent girls in Kenya: a comparison of interviewing methods. Sex Transm Infect. 2004;80 Suppl 2:ii43-8. -->
<!-- Cleland J, Boerma JT, Carael M, Weir SS. Monitoring sexual behaviour in general populations: a synthesis of lessons of the past decade. Sex Transm Infect. 2004;80 Suppl 2:ii1-7. -->
<!-- Helleringer S, Kohler HP, Kalilani-Phiri L, Mkandawire J, Armbruster B. The reliability of sexual partnership histories: implications for the measurement of partnership concurrency during surveys. AIDS. 2011;25(4):503-11.Mensch BS, Hewett PC, Erulkar AS. The reporting of sensitive behavior by adolescents: a methodological experiment in Kenya. Demography. 2003;40(2):247-68. -->
<!-- Then there’s the option of discussing validity of self-reported sexual behaviour based on biomarker validation (e.g. https://academic.oup.com/ofid/article/6/2/ofz010/5285444, there are more like this) but I’m not super familiar with this literature to pull a reference that would be appropriate. -->

The risk groups we analysed did not consider other important characteristics, such as condom usage or partner-specific risk, which contribute to heterogeneity within each risk group.
Although the number of risk groups considered could be increased, capturing more of this heterogeneity, this inclination must be balanced with the benefits of parsimony.
Our approach assumed that within risk group heterogeneity is small enough that the categories are meaningfully consistent across contexts.
Additionally, the categories we used are not immediately actionable.
For example, a program is designed to reach AGYW who are cohabiting, then it is not clear how to find these individuals within a community.
As such it may be preferable to select risk groups based more amenable attributes, such as attendance of a particular service or facility.
% e.g. school, healthcare

Finally, our analysis focused only on females aged 15-29 years and therefore did not consider optimisation of prevention for the wider population of all adults of both sexes.
By limiting our consideration to this group we didn't account for `r "num"`\% of all new infections [CITE: Katie, others].
% Obtaining population size estimates for sexual risk behaviour in the general population is a crucial step toward greater understanding the dynamics of the HIV epidemic in sub-Saharan Africa, and would allow incidence models of greater fidelity to reality which include stratification of individuals by sexual risk.

<!-- Likely over-reporting of never having had sex in the past year by young women, if we apply an RR of 0 to this group, to balance out the overall incidence rate, might be over-attributing risk to the other groups. -->
<!-- Defining condom usage is challenging, particularly for those with multiple partners, and reporting is likely biased due to social desirability. -->
<!-- Additionally, consistent condom usage is rare amongst those cohabiting, and as such likely only relevant for those with non-regular sexual partners.  -->

## Conclusion

We estimated the proportion of AGYW aged 15-19, 20-24 and 25-29 years in four sexual risk categories at a district-level in 13 priority countries.
Using these estimates, we performed an analysis of the number of infections that could be reached by prioritisation based upon location, age and behaviour.
Though subject to limitations, our results quantify the crucial importance of reaching the AGYW at highest risk.

## Funding

AH was supported by the EPSRC Centre for Doctoral Training in Modern Statistics and Statistical Machine Learning (EP/S023151/1).
AH, VKN, KAR, JWE were supported by the Bill and Melinda Gates Foundation (OPP1190661, OPP1164897).
TMW was supported by Imperial College London (President's PhD Scholarship).
SF was supported by the EPSRC (EP/V002910/1).
JWE was supported by UNAIDS and National Institute of Allergy and Infectious Disease of the National Institutes of Health (R01AI136664). 

This research was supported by the MRC Centre for Global Infectious Disease Analysis (MR/R015600/1), jointly funded by the UK Medical Research Council (MRC) and the UK Foreign, Commonwealth \& Development Office (FCDO), under the MRC/FCDO Concordat program and is also part of the EDCTP2 programme supported by the European Union.

## Disclaimer

The findings and conclusions in this manuscript are those of the authors and do not necessarily represent the official position of the funding agencies.

# References {#references .unnumbered}
